### ISSUE TITLE
contradictions in page lengths

### ISSUE THREAD

**Issue by dvolgyes** [SFI-Visual-Intelligence/nldl#1]
Hi,

When we submitted the paper drafts in September, the call explicitly stated 6 pages papers
and a 7th for addressing review, see:
https://www.nldl.org/submission/call-for-papers

"a 6-page full paper (included in proceedings)"
"in the area of Deep Learning. References can go beyond the page limit."
"For the camera ready version of accepted papers, we allow the authors to add a 7th page to their paper in order to address requests from the reviewers"

While the current template states:
"or the camera ready, the authors can have 1 more page to address the comments from
the reviewers. That is, the page limit in the camera ready is 6 pages (in comparison to the 5 pages limit
in the original submission). Note that the appendix is still unlimited."

And it does'nt specify the status of references.  In extreme cases, the manuscript was revised for 7 pages + 1-2 pages of references, which according to the new template should be compressed into 6 pages (if references count into the page limit).

It's a bit exaggerated, the new layout is more compact, but still, the contradiction exists, and the status of references in the new template is not clear.

**Comment by adinriv** [comment]
Hi,

Given the update on the format the page limit was updated.  We compared the old layout to the new one, and that is where the new page limit comes from.  The references, acknowledgements, and appendix do not count towards the limit.

We will update the information about the references in the template.
